### ISSUE TITLE
It's not easy to understand of Dlang templete tags

### ISSUE THREAD

**Issue by stevenpan110** [huntlabs/hunt-framework-docs#11]
We are not all familiar with the two template tags of  Twig and Jinja2 syntax, so we hope to complete the template tags of D language

**Comment by stevenpan110** [comment]
Is there a switch method in the template？
What are the processing methods for the output fields in the template？

**Comment by betrixed** [comment]
Right now, I am exploring the hunt - dlang way of doing things. I have used dlang before, so it shouldn't be too much a learning curve. I am still looking through the source tree in the .dub/packages and guessing. 

I have a Website in PHP.  A common idiom is to do a  database query, and pass results to a template  as array of record objects, or array of array of key-value pairs.

Please, in your documentation, show how to pass results from
generic query for a record set with multiple fields, and multiple rows.

So I can get a query result, but how best to generate a template which can iterate multiple data rows?
At the moment, the view documentation suggests  view.assign supports a named string value, or a named associative array, string[string].
There seems to be a possibility of the template execution being aware of the interfaces of the EntityRepository, ORM , and be able to iterate using the template macros.
I realize that interpreted AST templates will have limits, and this one would be a priority for any further progress for me.
It isn't easy, as some other project would have managed it already.

**Comment by Heromyth** [comment]
Here is a simple demo for `table binding` in View:
https://github.com/huntlabs/hunt-examples/blob/master/website-basic/source/app/controller/IndexController.d#L557
https://github.com/huntlabs/hunt-examples/blob/master/website-basic/views/default/index.dhtml#L37

More about the syntax of View, see https://github.com/huntlabs/hunt-framework/wiki/View.
