### ISSUE TITLE
not found the file dub.json

### ISSUE THREAD

**Issue by stevenpan110** [huntlabs/hunt-framework-docs#3]
If i first install hunt and choose the sdl format,
then  the file of  dub.json can not be find in my project，
but the doc need you to add executable to your dub.json

**Comment by hanfengfg** [comment]
Please select `json` format，has been update content [install.d](https://github.com/huntlabs/hunt-framework-docs/blob/master/installation.md#linux-installing-Hunt)
```shell
# dub init 
Package recipe format (sdl/json) [json]: json
```
