### ISSUE TITLE
./examples serve -e test  does‘t work

### ISSUE THREAD

**Issue by stevenpan110** [huntlabs/hunt-framework-docs#6]
You can also specify the configuration file to use from the command line, for example, to start a project using the command line and specify the configuration file application.test.conf:
./examples serve -e test
[https://github.com/huntlabs/hunt-framework-docs/blob/master/configuration.md](url)

**Comment by Heromyth** [comment]
Fixed in commit https://github.com/huntlabs/hunt-framework/commit/c2912ec97589bb45220697612940f8048976db8b.

**Comment by Heromyth** [comment]
The correct usage is `./examples serve -e=test`.
