### ISSUE TITLE
string name() is the a construct function？

### ISSUE THREAD

**Issue by stevenpan110** [huntlabs/hunt-framework-docs#9]
#Defining Middleware

string name() {
        return CheckAgeMiddleware.stringof;
    }

[https://github.com/huntlabs/hunt-framework-docs/blob/master/middleware.md](url)

**Comment by stevenpan110** [comment]
What is '.stringof' used for?

**Comment by Heromyth** [comment]
string representing the source representation of the type ,indicates the type of string
